### ISSUE TITLE
[BUG] cargo make test-yaml fails on MacOS - MAC verification failed during PKCS12 import

### ISSUE THREAD

**Issue by dblock** [opensearch-project/opensearch-rs#119]
### What is the bug?

Running `cargo make test-yaml` fails on MacOS with 

```
---- free::bulk::_11_basic_with_types::array_of_objects stdout ----
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Cert(reqwest::Error { kind: Builder, source: Error { code: -25264, message: "MAC verification failed during PKCS12 import (wrong password?)" } })', yaml_test_runner/tests/common/client.rs:96:37
```

Subsequent tests all fail with 

```
---- free::bulk::_11_basic_with_types::empty_action stdout ----
thread 'main' panicked at 'Lazy instance has previously been poisoned', /Users/dblock/.cargo/registry/src/github.com-1ecc6299db9ec823/once_cell-1.17.0/src/lib.rs:1276:25
---
```

Likely both are separate problems.

### How can one reproduce the bug?

```
OPENSEARCH_URL=https://localhost:9200 STACK_VERSION=1.3.4 cargo make test-yaml
```

### What is the expected behavior?

- Tests to pass.
- Subsequent tests to run and fail with a real error.

### What is your host/environment?

```
Darwin b0f1d8717713 21.6.0 Darwin Kernel Version 21.6.0: Thu Sep 29 20:13:56 PDT 2022; root:xnu-8020.240.7~1/RELEASE_ARM64_T6000 arm64

```

### Do you have any additional context?

This seems to be https://stackoverflow.com/questions/70431528/mac-verification-failed-during-pkcs12-import-wrong-password-azure-devops, but setting PATH as described doesn't seem to have any effect.

**Comment by Xtansia** [comment]
This will be fixed in #128 as I also hit this verifying things locally. 
Seems to be a combination of things:
- On MacOS [rust-native-tls](https://github.com/sfackler/rust-native-tls) uses the security framework rather than OpenSSL directly.
- The MacOS security framework has poor support for "modern" ciphers and such used by default in OpenSSL 3
- Even when targeting the default legacy setting used by MacOS SSL (`RC2-40`) it still does not play well when the PKCS12 has no password
- If we target `RC2-40` with a password, then OpenSSL3 will barf due to it being moved to the legacy provider

Solution I've found is to add a password & target `DES3` which is happily supported by MacOS and modern OpenSSL.
